name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # DEPLOY DIRETO, sem build (para HTML/CSS/JS simples)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANALIVIA_CB075 }}'
          channelId: live
          projectId: analivia-cb075
